AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A AWS EC2 instances and spot requests count expoter for prometheus
Resources:
  Metrics:
    Type: AWS::Serverless::Function
    Properties:
      Description: A AWS EC2 instances and spot requests count expoter for prometheus
      CodeUri: ./src
      Handler: main.handler
      Runtime: python3.6
      Timeout: 30
      Policies: AmazonEC2ReadOnlyAccess
      Events:
        Api:
          Type: Api
          Properties:
            Path: /metrics
            Method: get
